openxml/openxml-package

lib/openxml/builder.rb
Function is included in ActiveSupport, which is loaded in development, but required by `builder.rb` for normal operation.
=> Added extract_options! extension to Array

lib/openxml/builder.rb, lib/openxml/builder/element.rb, lib/openxml/builder/namespace.rb, lib/openxml/part.rb, test/part_test.rb
Extends `Ox::Node` to have a concept of parent and `Ox::HasAttrs` to include the idea of namespaces. `OpenXml::Builder` has been modified to implement the same sort of DSL as Nokogiri's builder class with regards to namespaces.
=> Added basic namespace support using Ox

lib/openxml/parts/content_types.rb
This pull request uses the correct syntax for parsing XML documents with Nokogiri.
See http://www.nokogiri.org/tutorials/parsing_an_html_xml_document.html
A consequence is that this allows the Package.read method to work properly.
=> Use Correct Syntax for Nokogiri Parsing

README.md
I found typo.
> doc = OpenXmlPackage.open("~/Desktop/output.zip")
NoMethodError: private method `open' called for OpenXmlPackage:Module
=> fix wrong reading usage

lib/openxml/package.rb
The defaults and overrides for content types were global to a package.
That means that if we add more at runtime they end up added to all
packages created after that point. We want to only add them to an
instance of package.
The A Team
=> Fix issue with global content types stepping on each other

lib/openxml/parts/rels.rb, lib/openxml/relationship.rb
This is because in some cases it is nice to not build a new rels each
time you push a rel. This means that the rels can have the same ref ids
no matter what rel file they are in. This will also reduce memory
footprint and time.
Amos King @adkron <amos@binarynoggin.com>
=> Allow relationships to be built outside of rels

lib/openxml/has_attributes.rb, lib/openxml/has_children.rb, lib/openxml/has_properties.rb, test/has_properties_test.rb
Curious what you think of the API. It seemed intuitive to me to have the methods available to get/set directly on the element with properties so that you can set these "properties attributes" as if they were normal properties, but then the actual handling of having attributes on the properties tag itself is handled by a normal `OpenXml::Element`.
=> Properties Attributes

lib/openxml/properties.rb, lib/openxml/properties/base_property.rb, lib/openxml/properties/boolean_property.rb, lib/openxml/properties/complex_property.rb, lib/openxml/properties/container_property.rb, lib/openxml/properties/integer_property.rb, lib/openxml/properties/on_off_property.rb, lib/openxml/properties/positive_integer_property.rb, lib/openxml/properties/string_property.rb, lib/openxml/properties/toggle_property.rb, lib/openxml/properties/transparent_container_property.rb, lib/openxml/properties/value_property.rb
This mostly copies over the base properties classes from `OpenXml::Docx`. The major changes were related to the `to_xml` methods, removing the default `:w` namespace and allowing for entirely non-namespaced properties.
=> Property classes

lib/openxml/contains_properties.rb, lib/openxml/has_properties.rb, lib/openxml/properties/on_off_property.rb, lib/openxml/properties/value_property.rb, test/contains_properties_test.rb, test/has_properties_test.rb
Replaces #21 
From that PR's description:
This allows for `OpenXml::Elements` to behave as the properties tag when necessary. This allows for some edge cases that come up in PresentationML and DrawingML. First, the case where the properties tag differs in namespace from its container:
```xml
<p:txBody>
<a:bodyPr/>
</p:txBody>
```
Secondly, the case where you want multiple properties tags within the same container:
```xml
<p:defaultTextStyle>
<a:defPPr/>
<a:lvl1pPr/>
</p:defaultTextStyle>
```
=> Added ContainsProperties Module

lib/openxml/has_properties.rb, test/has_properties_test.rb
This would allow properties to be grouped as mutually-exclusive choices. It allows us to enforce with exceptions `<xsd:choice/>` designations in the OpenXml spec.
For example, when designating a color in DrawingML, one has a choice of: `<scrgbClr/>`, `<srgbClr/>`, `<hslClr/>`, `<sysClr/>`, `<schemeClr/>`, and `<prstClr/>`. Each of these are properly separate properties with their own attributes (and in some cases properties of their own!), but only _one_ may be used as a child of some element looking for a color.
---
I'm not 100% on the first commit. The mechanism for assigning a tag in this way is already there, but the second commit, I _think_, mostly obviates the need for this kind of polymorphism, since we can either create a choice group and/or use inheritance to change tags as …
=> Property Choice

lib/openxml/has_properties.rb
This allows for using properties from one type of ML in the elements of another. E.g., using DrawingML properties in a PresentationML element.
=> Specify A Property's Class

lib/openxml/properties/container_property.rb
Just `Properties` before was searching the `OpenXml::Properties` module for the generated class name, even when operating from a sublcass in a different scope.
=> Correctly Scoped Container Property Child Classes

lib/openxml/has_attributes.rb, lib/openxml/has_properties.rb, test/has_attributes_test.rb, test/has_properties_test.rb
I thought about trying to make other important class-level instance variables inheritable also, e.g., `tag` and `namespace`; however, I opted to omit those, as it's probably better for documentation purposes to have to specify those even on a subclass...
=> Inheritable attributes

lib/openxml/has_attributes.rb, lib/openxml/has_properties.rb
Adds `required:` parameters to properties, attributes, and property choices. As of yet, these are unimplemented and so will warn the consuming package as such (but not raise an exception).
=> Required placeholders

lib/openxml/has_attributes.rb, lib/openxml/has_properties.rb
Based on #31. Relevant commit 3365940.
`render_properties?` would return `true` if any properties attributes were specified, ignoring whether or not they were actually set, resulting in an empty properties element (e.g., `<a:pPr/>`) where before there would not be one.
=> No empty properties elements

lib/openxml/contains_properties.rb, lib/openxml/has_attributes.rb, lib/openxml/has_properties.rb, lib/openxml/render_when_empty.rb, test/has_properties_test.rb
Still no implementation on required attributes or `property_choice` groups. Part of me wants to raise an exception at render if required elements are not defined (including required properties and value properties), but I'm not sure what kind of mechanism should be used to get around that requirement for testing.
There are a few extra fixes that found their way into this branch also. They're pretty small, but I can pull them out into their own PR if necessary.
=> Added method to build out required properties

openxml-package.gemspec
Updated the rubyzip gem dependency in response to CVE:
https://nvd.nist.gov/vuln/detail/CVE-2018-1000544
=> Bumped rubyzip dependency to 1.2.2

lib/openxml/package.rb
For Windows, `write_to` in [openxml-package/package.rb](https://github.com/openxml/openxml-package/blob/master/lib/openxml/package.rb) should be:
```rb
def write_to(path)
File.open(path, "wb") do |file|
file.write to_stream.string
end
end
alias :save :write_to
```
because the current `write_to` writes a broken docx file that MS Word cannot open correctly.
Note:
- `File.open(path, "w")`: 'text mode' in Windows
- `File.open(path, "wb")`: 'binary mode' in Windows (`b` is ignored in Unix)
Then this fix should not affect to Unix environments.
Given:
-`xml` (new OOXML string at word/style.xml to be written)
- `docx_path` (file path to input docx)
- `output_path` (file path to output docx)
This code below doesn't work:
```rb
OpenXml::Package.open(docx_path) do |package|
package.add_part …
```
=> [fix] write_to writes binary both in Unix and Windows

openxml-package.gemspec
This will allow apps depending on this gem to upgrade to the latest, patched version of Rubyzip
=> Unpinned rubyzip dependency

.github/workflows/ci.yml, .travis.yml, test/test_helper.rb
- Remove Travis CI configuration
- Add GitHub Actions workflow to test with all compatible Ruby versions
- Avoid errors in rr
=> Replace Travis CI with GitHub Actions for running tests
